### PR TITLE
fix WaitReady error return

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

### Ⅰ. Describe what this PR does
fix WaitReady error return

### Ⅱ. Does this pull request fix one issue?

fix WaitReady error return

### CODE REVIEW

**Comment by FillZpp** [comment]
@yxxhero The returning error was removed in https://github.com/openkruise/kruise/pull/843 , for sometimes we don't know how long it costs to initialize cache in large-scale clusters.

**Comment by yxxhero** [comment]
oh. I known. Will the startup of this webhook affect the mainstream program? @FillZpp Thanks very much.

**Comment by FillZpp** [comment]
> oh. I known. Will the startup of this webhook affect the mainstream program? @FillZpp Thanks very much.

Yes, if the mainstream program you mean controllers of kruise. Controllers will fail to create/update some CRs if the webhook has not started.

**Pull request closed without merging**
