### PR TITLE
fix: initContainers shareVolumePolicy is not effective

### LINKED ISSUE #1216: [BUG] initContainers shareVolumePolicy is not effective
**What happened**:
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  initContainers:
  - name: sidecar1
    image: busybox
    command: ["sleep", "1"]
    shareVolumePolicy:
      type: enabled
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes:
  - name: log-volume
    emptyDir: {}
```

the result is :
```
spec:
  containers:
  - image: nginx:alpine
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /test
      name: test
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sttkv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sleep
    - "1"
    env:
    - name: IS_INJECTED
      value: "true"
    image: busybox
    imagePullPolicy: Always
    name: sidecar1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sttkv
      readOnly: true
```

no volume shared

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kruise version:1.3.0
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

### PR DESCRIPTION
**Pull request by y-ykcir**
### Ⅰ. Describe what this PR does
fix initContainers shareVolumePolicy is not effective

### Ⅱ. Does this pull request fix one issue?

fix #1216 

### Ⅲ. Describe how to verify it
Refer to the issue

### CODE REVIEW

**Comment by zmberg** [comment]
@y-ykcir tks, can you add some ut in [code](https://github.com/openkruise/kruise/blob/master/pkg/webhook/pod/mutating/sidecarset_test.go#L729)?

**Comment by y-ykcir** [comment]
> @y-ykcir good, can you add some ut in [code](https://github.com/openkruise/kruise/blob/master/pkg/webhook/pod/mutating/sidecarset_test.go#L729)?

ok, I'll add some ut.

**Comment by y-ykcir** [comment]
@zmberg PTAL

**Pull request merged**
