### PR TITLE
fix: validate update AdvancedDaemonSet

### PR DESCRIPTION
**Pull request by hantmac**
### Ⅰ. Describe what this PR does
Fix https://github.com/openkruise/kruise/issues/1498

### Ⅲ. Describe how to verify it
Run test `TestValidateDaemonSetUpdate ` or update Advanced DaemonSet  `Spec.Selector` will get error

### CODE REVIEW

**Comment by zmberg** [comment]
@hantmac your UT coverage is estimated to be a bit fuller.
image

**Comment by hantmac** [comment]
> @hantmac your UT coverage is estimated to be a bit fuller. image

[These test](https://github.com/openkruise/kruise/pull/1505/files#diff-9465d2cd5aaea6b9853c0896766dad4b3618f828d5e6933082c39c8f05f17843R113) cover the added code. I can't add more UT 😢

**Comment by furykerry** [comment]
> These test cover the added code. I can't add more UT

can you modify the UT to invoke DaemonSetCreateUpdateHandler.Handle function, UT should cover the published function

**Comment by hantmac** [comment]
> > These test cover the added code. I can't add more UT
> 
> can you modify the UT to invoke DaemonSetCreateUpdateHandler.Handle function, UT should cover the published function

It sounds somewhat unreasonable. It seems like for the sake of UT, just UT 🤔

**Review by furykerry — COMMENTED** [review]
/lgtm

**Pull request merged**
