### PR TITLE
Generic AdvancedCronJob CRD & Controller proposal

### PR DESCRIPTION
**Pull request by rishi-anand**
### Ⅰ. Describe what this PR does
Implement CRD and controller for `BroadcastCronJob`

### Ⅱ. Does this pull request fix one issue?

#215

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
This is proposal. Will add test cases in implementation.

### Ⅳ. Describe how to verify it
This is proposal. Will add more information in implementation PR.

### Ⅴ. Special notes for reviews
Discussion: https://github.com/openkruise/kruise/issues/215#issuecomment-715506813
Implementation PR: https://github.com/spectrocloud/kruise/pull/1

@Fei-Guo, @FillZpp Please review

### CODE REVIEW

**Review by Fei-Guo — COMMENTED** [review]
Would it make sense to extend upstream CronJob to support BroadcastJob? 

We can call it AdvancedCronJob which supports both upstream Job and BroadcastJob. 
I think when you implement the controller, most of the code will be duplicated with upstream CronJob anyway.

**Comment by rishi-anand** [comment]
@Fei-Guo, CronJob native controller is already there which supports Job. We need a cron controller for just  BroadcastJob. 
Thus, I have created a CRD BroadcastCronJob which will be upstream cron controller for BroadcastJob.

I have implemented and tested the controller. PR: https://github.com/spectrocloud/kruise/pull/1

**Comment by Fei-Guo** [comment]
What I meant is to have a controller to support both native job and broadcastjob so that people can use one controller for all cron type workloads. It is also possible we will have other types of Jobs in the futures so that the new cron controller can be extended to support new job types as well.

**Comment by rishi-anand** [comment]
@Fei-Guo, Few parameters may be different for Job, BroadcatJob, or future CRD. From an implementation perspective, Should we have multiple template object in the spec of AdvancedCronJob or should it have reference to other CRD?

**Comment by Fei-Guo** [comment]
> @Fei-Guo, Few parameters may be different for Job, BroadcatJob, or future CRD. From an implementation perspective, Should we have multiple template object in the spec of AdvancedCronJob or should it have reference to other CRD?

I would suggest to have multiple templates, which is more clearer. Of course, only one of them takes effect is multiple templates are specified and the spec should not be mutated once it is created.

**Comment by rishi-anand** [comment]
Sure @Fei-Guo. I will make respective changes in the proposal docs.

**Comment by rishi-anand** [comment]
@Fei-Guo, Modified proposal to have below points and other related changes.

```
## Proposal

- Adding a new CRD and controller for AdvancedCronJob.
- AdvancedCronJob should be able to reconcile Job/BroadcastJob or any other future CRD if required.
- Once AdvancedCronJob is created, spec cannot be modified.
- Adding webhook for validation of AdvancedCronJob.
```

**Comment by Fei-Guo** [comment]
@rishi-anand Can you rebase your PR please?

**Comment by rishi-anand** [comment]
@Fei-Guo, Somehow this PR got bit messed up. I have created another PR for proposal.
PR: https://github.com/openkruise/kruise/pull/437

**Pull request closed without merging**
