### PR TITLE
Adding roadmap for Q3 2019.

### PR DESCRIPTION
**Pull request by Fei-Guo**
### Ⅰ. Describe what this PR does

Add the Kruise development roadmap for next three months.

### Ⅱ. Does this pull request fix one issue?

issue #18

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

Doc only， no code change.

### Ⅳ. Describe how to verify it

N/A

### Ⅴ. Special notes for reviews
N/A

### CODE REVIEW

**Comment by xiang90** [comment]
@Fei-Guo Can we create a Roadmap section in the Readme.md in the root dir? 

We need to make the roadmap discoverable from the front page.

**Comment by xiang90** [comment]
lgtm otherwise.

**Comment by Fei-Guo** [comment]
> @Fei-Guo Can we create a Roadmap section in the Readme.md in the root dir?
> 
> We need to make the roadmap discoverable from the front page.

Sure, I'd prefer to doing it in a separate change.

**Comment by Fei-Guo** [comment]
> Should be mutating

Yes, thanks for pointing out!

**Comment by xiang90** [comment]
sgtm. Probably @jian-he or @allencloud can give this a final review before merging.

**Comment by jian-he** [comment]
LGTM

**Pull request merged**
