### PR TITLE
fix: replace deadcode with unused and address existing issues

### PR DESCRIPTION
**Pull request by hezhizhen**
Signed-off-by: Zhizhen He <hezhizhen.yi@gmail.com>

### Ⅰ. Describe what this PR does

`deadcode` is deprecated so I replace it with `unused`. Then I address some existing issues.

### CODE REVIEW

**Comment by zmberg** [comment]
@hezhizhen Please run "make generate manifests" and push again.

**Comment by hezhizhen** [comment]
> @hezhizhen Please run "make generate manifests" and push again.

You can see my last commit. That's the result of this command. I don't know why...

**Comment by zmberg** [comment]
> > @hezhizhen Please run "make generate manifests" and push again.
> 
> You can see my last commit. That's the result of this command. I don't know why...

@hezhizhen Is your version of golang 1.18 ?

**Comment by hezhizhen** [comment]
> > > @hezhizhen Please run "make generate manifests" and push again.
> 
> > 
> 
> > You can see my last commit. That's the result of this command. I don't know why...
> 
> 
> 
> @hezhizhen Is your version of golang 1.18 ?

It's 1.19. I will use 1.18 to generate.

**Comment by hezhizhen** [comment]
> > > > @hezhizhen Please run "make generate manifests" and push again.
> > 
> > 
> > > 
> > 
> > 
> > > You can see my last commit. That's the result of this command. I don't know why...
> > 
> > 
> > @hezhizhen Is your version of golang 1.18 ?
> 
> It's 1.19. I will use 1.18 to generate.

Done. PTAL. @zmberg

**Review by uzairmaqsood — APPROVED** [review]

**Pull request merged**
