### PR TITLE
Fix broadcastjob expectation observed when node assigned by scheduler

### LINKED ISSUE #580: broadcastjob 状态不对，无法自动删除
Kruise 版本：0.8.0

Kubernetes 版本：1.18.16

broadcastjob 配置及状态：
spec:
  completionPolicy:
    activeDeadlineSeconds: 600
    ttlSecondsAfterFinished: 30
    type: Always
  failurePolicy:
    type: FailFast
  parallelism: 2147483647
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
            ......
status:
  active: 8
  desired: 8
  failed: 0
  phase: running
  startTime: "2021-04-02T08:05:00Z"
  succeeded: 0

pod 状态：
[root@kube-node-1810-01 ~]# kubectl get pod -n kruise-instance
NAME                                                         READY   STATUS      RESTARTS   AGE
cronjob-broadcastjob-prune-expired-images-1617350700-4w58x   0/1     Error       0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-577fv   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-5rpp9   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-cqx2p   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-mmv8d   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-mwbwm   0/1     Error       0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-tk67q   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350700-xfx49   0/1     Completed   0          3m16s
cronjob-broadcastjob-prune-expired-images-1617350760-99jnz   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-9tt8m   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-fhjn5   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-lt5c8   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-sfbz5   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-st4wj   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-wmpc8   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350760-zhs6z   0/1     Completed   0          2m16s
cronjob-broadcastjob-prune-expired-images-1617350820-4lqjn   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-89k8l   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-kzg6g   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-mspd8   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-mvh26   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-prhrl   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-qp44g   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350820-w4bwj   0/1     Completed   0          76s
cronjob-broadcastjob-prune-expired-images-1617350880-ds2q8   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-hx5c7   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-ld6vj   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-md52k   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-mk2cs   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-mrjcs   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-nqgsf   0/1     Completed   0          16s
cronjob-broadcastjob-prune-expired-images-1617350880-pbpwf   0/1     Completed   0          16s

[root@kube-node-1810-01 ~]# kubectl get broadcastjobs.apps.kruise.io -n kruise-instance
NAME                                                   DESIRED   ACTIVE   SUCCEEDED   FAILED   AGE
cronjob-broadcastjob-prune-expired-images-1617350700   8         8        0           0        3m26s
cronjob-broadcastjob-prune-expired-images-1617350760   8         8        0           0        2m26s
cronjob-broadcastjob-prune-expired-images-1617350820   8         8        0           0        86s
cronjob-broadcastjob-prune-expired-images-1617350880   8         8        0           0        26s

### LINKED ISSUE #582: [BUG] broadcastJob reconcile failed
**What happened**:
I create a `broadcatJob` use next yaml:

```
apiVersion: apps.kruise.io/v1alpha1
kind: BroadcastJob
metadata:
  name: broadcastjob-ttl
spec:
  parallelism: 2
  template:
    spec:
      tolerations:
       - effect: NoSchedule
         key: reserved
         operator: Equal
         value: cd-staging
      containers:
        - name: pi
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  completionPolicy:
    type: Always
    ttlSecondsAfterFinished: 10
```
BUT, the `broadcastJob` stop in the next status:

image
 

**What you expected to happen**:

I want the `bcj` run until all the job (number of node) completed.

**How to reproduce it (as minimally and precisely as possible)**:

Use the yaml above to create a bcj.

**Anything else we need to know?**:

**Environment**:  k8s 1.18
- Kruise version: v0.8.0
- Kubernetes version (use `kubectl version`): 1.18

The I use source to debug it, I found a bug in https://github.com/openkruise/kruise/blob/6dae2c5d348c53332bafb5249864b2ffbcf43c06/pkg/controller/broadcastjob/broadcastjob_controller.go#L163 , every time I start the controllers, then creating a new bcj, the `broadcast controller` only make sense once and It's blocked on that line of code , 
image

because  in code `scaleSatisfied, unsatisfiedDuration, scaleDirtyPods :=scaleExpectations.SatisfiedExpectations(request.String());` the `scaleSatisfied` always be false, so the reconcile cannot continue  .

If i comment that code, all things ok, so I have a question, why broadcastJob need `SatisfiedExpectations` ?

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

### Ⅰ. Describe what this PR does
Fix broadcastjob expectation observed when node assigned by scheduler

### Ⅱ. Does this pull request fix one issue?

fixes #580 
fixes #582 

### Ⅴ. Special notes for reviews
The problem is caused by #498 . When Pod is assigned by scheduler, the event handler could not get the right node name from `pod.Spec.NodeName` field.

### CODE REVIEW

**Review by Fei-Guo — APPROVED** [review]
LGTM

**Comment by hantmac** [comment]
I think the unit test cases for broadcastjob should  be optimized.
The `parallelism` field in test cases always bigger than the number of node, so this bug can't be found.

**Comment by FillZpp** [comment]
> I think the unit test cases for broadcastjob should be optimized.
> The `parallelism` field in test cases always bigger than the number of node, so this bug can't be found.

Thanks. Since it is hard to verify the event handler in unit-test because of no real list-watch, I have added an e2e case for it.

**Review by Fei-Guo — APPROVED** [review]

**Pull request merged**
