### PR TITLE
some adjustment for cloneset update validation

### PR DESCRIPTION
**Pull request by dylandee**
1. use Semantic.DeepEqual instead of reflect.DeepEqual
2. revisionHistoryLimit should be editable like native deployment
3. complete forbidden hint

### CODE REVIEW

**Review by Fei-Guo — DISMISSED** [review]

**Comment by Fei-Guo** [comment]
Please fix ci error.

**Comment by dylandee** [comment]
> Please fix ci error.

Sry, my fault. Problem fixed

**Comment by Fei-Guo** [comment]
> > Please fix ci error.
> 
> Sry, my fault. Problem fixed

There is a UT failure as well. It seems to be related with your change.

**Comment by dylandee** [comment]
> > > Please fix ci error.
> > 
> > 
> > Sry, my fault. Problem fixed
> 
> There is a UT failure as well. It seems to be related with your change.

Done

**Comment by FillZpp** [comment]
@dylandee I suggest you can modify the commit message to something like `allow to update revisionHistoryLimit in cloneset validation`. It is more clear than `some adjustment`.

**Comment by dylandee** [comment]
> @dylandee I suggest you can modify the commit message to something like `allow to update revisionHistoryLimit in cloneset validation`. It is more clear than `some adjustment`.

i

**Pull request closed without merging**
