### PR TITLE
Some  clean ups

### PR DESCRIPTION
**Pull request by hantmac**
Signed-off-by: hantmac <hantmac@outlook.com>

### Ⅰ. Describe what this PR does

- Clean ups
- Unhandled error

### CODE REVIEW

**Comment by Fei-Guo** [comment]
I am just curious about how can unhealthy is > 0 but firstUnhealthyPod is nil ptr?

**Comment by hantmac** [comment]
> I am just curious about how can unhealthy is > 0 but firstUnhealthyPod is nil ptr?

Because `firstUnhealthyPod`  is assigned when meet the condition `ord := getOrdinal(condemned[i]); ord < firstUnhealthyOrdinal` , if not, `firstUnhealthyPod` is nil.
```go
.......
unhealthy++
			if ord := getOrdinal(condemned[i]); ord < firstUnhealthyOrdinal {
				firstUnhealthyOrdinal = ord
				firstUnhealthyPod = condemned[i]
			}
```

**Comment by Fei-Guo** [comment]
> > I am just curious about how can unhealthy is > 0 but firstUnhealthyPod is nil ptr?
> 
> Because `firstUnhealthyPod` is assigned when meet the condition `ord := getOrdinal(condemned[i]); ord < firstUnhealthyOrdinal` , if not, `firstUnhealthyPod` is nil.
> 
> ```go
> .......
>                           unhealthy++
> 			if ord := getOrdinal(condemned[i]); ord < firstUnhealthyOrdinal {
> 				firstUnhealthyOrdinal = ord
> 				firstUnhealthyPod = condemned[i]
> 			}
> ```

Yes. I just don't see how can the condition never met once given that firstUnhealthyOrdinal is initialized with MAX_INT.

**Comment by Fei-Guo** [comment]
https://github.com/kubernetes/kubernetes/blob/475849eafaafb653c6c238d4947b7c17f191afee/pkg/controller/statefulset/stateful_set_control.go#L371 

This is the same as the the upstream code.  It is possible that upstream has a bug as well. I just want to double check the possible logic error here.

**Comment by hantmac** [comment]
> https://github.com/kubernetes/kubernetes/blob/475849eafaafb653c6c238d4947b7c17f191afee/pkg/controller/statefulset/stateful_set_control.go#L371
> 
> This is the same as the the upstream code. It is possible that upstream has a bug as well. I just want to double check the possible logic error here.

I opened an issue  https://github.com/kubernetes/kubernetes/issues/95507 , and the k8s maintainer said this null is not a valid bug.

**Comment by Fei-Guo** [comment]
I am assuming you want to turn this PR to a clean up change. Please update the PR title and PR description accordingly. 

Thanks

**Review by Fei-Guo — APPROVED** [review]
LG. Thanks for working on this.

**Pull request merged**
