### PR TITLE
changed the scorecard badge link to the standard format

### PR DESCRIPTION
**Pull request by harshitasao**
### Ⅰ. Describe what this PR does

Changes the scorecard badge link from old format to the Standard human-readable OpenSSF Scorecard Report.

### Ⅱ. Does this pull request fix one issue?

N/A

### Ⅲ. Describe how to verify it
N/A

### Ⅳ. Special notes for reviews
N/A

### CODE REVIEW

**Comment by furykerry** [comment]
thanks for your patch. however when we visit the new link, it is not working and shows the following error
"Something went wrong fetching the Scorecard Report data

Status code: undefinedundefined"

**Comment by furykerry** [comment]
plz squash the commits into one

**Comment by harshitasao** [comment]
Hi, I checked this on my branch and it's working correctly, showing a score of 8.4.

**Pull request merged**
