### PR TITLE
Fix security vulnerability caused by x/net package

### PR DESCRIPTION
**Pull request by veophi**
Signed-off-by: mingzhou.swx <mingzhou.swx@alibaba-inc.com>

### Ⅰ. Describe what this PR does

image

### CODE REVIEW

**Review by furykerry — COMMENTED** [review]
/lgtm

**Comment by fengshunli** [comment]
see https://github.com/openkruise/kruise/pull/1165 @veophi @furykerry

**Comment by veophi** [comment]
> see #1165 @veophi @furykerry

@fengshunli feng  thanks, I will close my pr.

**Pull request closed without merging**
