### PR TITLE
Update link to correct guestbook v2 yaml

### PR DESCRIPTION
**Pull request by lachie83**
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

### Ⅰ. Describe what this PR does

Fixes incorrect link is advanced statefulset walkthrough - https://github.com/openkruise/kruise/blob/master/docs/tutorial/advanced-statefulset.md#inplace-update-guestbook-to-the-new-image

### Ⅱ. Does this pull request fix one issue?
No

### Ⅳ. Describe how to verify it

Follow demo on - https://github.com/openkruise/kruise/blob/master/docs/tutorial/advanced-statefulset.md#install-guestbook-application

### CODE REVIEW

**Comment by lachie83** [comment]
Associated diff 

```
diff  <(curl -Ls https://raw.githubusercontent.com/kruiseio/kruise/master/docs/tutorial/v1/guestbook-statefulset.yaml) <(curl -Ls https://raw.githubusercontent.com/kruiseio/kruise/master/docs/tutorial/v1/guestbook-statefulset-v2.yaml)
25c25
<         image: openkruise/guestbook:v1
---
>         image: openkruise/guestbook:v2
36a37
>       partition: 15
```

**Comment by lachie83** [comment]
Looking at this further I think the issue is that half the doc was written with the result of the Helm chart and the other half was written when using the the YAML files. Either we make the outputs of both the same OR document both e2e experiences

**Comment by jian-he** [comment]
hi @lachie83 , thanks for reporting the issue. 
Did you install the app using helm with `demo-v1` as the name

https://github.com/openkruise/kruise/blob/809afd09efc15d5acb01c21329c4d9c2a7d1a5e0/docs/tutorial/advanced-statefulset.md#installing-the-guestbook-application-using-helm

**Comment by lachie83** [comment]
I installed using the YAML files

**Comment by jian-he** [comment]
I see, 
This looks good to me, we'll change the helm chart with the same name.

Thanks

**Comment by resouer** [comment]
Ref https://github.com/openkruise/kruise/issues/42 so we can clean up the tutorial from workshops.

**Pull request merged**
