### PR TITLE
fix sidecarset status update

### PR DESCRIPTION
**Pull request by andrewshaoyu**
### Ⅱ. Does this pull request fix one issue?

#825

### CODE REVIEW

**Comment by FillZpp** [comment]
@andrewshaoyu Thanks for fixing it. The DCO check failed, which means you execute git commit without -s to sign yourself.

So you might have to `git commit --amend -s` and then force push again.

**Comment by FillZpp** [comment]
/lgtm
PTAL @zmberg

**Comment by FillZpp** [comment]
@zmberg You may have to apply `/approve` to merge it.

**Comment by andrewshaoyu** [comment]
What's wrong？

**Comment by zmberg** [comment]
@andrewshaoyu 
Because sidecarSet will manage hundreds of thousands of pods under some scenarios, for examples: logtail container. if every Pod ready changes will result in the overall calculation of all the pods, which will bring great pressure to the controller. And in the NotUpdate type, the user should not actually depend on the number of ready pods. So, we're going to have to think about this a little bit.

**Comment by andrewshaoyu** [comment]
That means NotUpdate type is usually used when sidecars do not affect pod status like log container?Now I use sidecarset to inject envoy with NotUpdate type, I do not want to rolling update Pods.

To reduce update presure, I think we can try to compress event with a period, within the period, only trigger sidecarset status update once. 

And add a field statusUpdateStrategy, that indicate whether the sidecarset status need to update.

**Comment by zmberg** [comment]
> And add a field statusUpdateStrategy, that indicate whether the sidecarset status need to update.
@FillZpp @furykerry What do you think, can add a type OnlyUpdateStatus to satisfy the user's scenario? For NotUpdate, sidecarSet status is no longer evaluated and triggered.

**Comment by FillZpp** [comment]
> What do you think, can add a type OnlyUpdateStatus to satisfy the user's scenario? For NotUpdate, sidecarSet status is no longer evaluated and triggered.

I don't think `OnlyUpdateStatus` is a good design, for fields like `matchedPods` in sidecarset status should be correct event if it's `NotUpdate` type. What we concern is that handling events triggered by pod status changed to update `readyPods` and `updatedReadyPods` might increase controller pressure.

Compress event with a period may be an optional way, you can add the sidecarset caused by pod status changed into queue with a duration. But question is how long the duration should be and status delay could you accept? @andrewshaoyu

**Comment by andrewshaoyu** [comment]
Make it configurable , default value 10s?

**Pull request closed without merging**
