### PR TITLE
fix no test cases actually run in controller_revision_test file

### LINKED ISSUE #1456: [BUG]  no test cases actually run in controller_revision_test file
**What happened**:

No tests actually run when you run the cmd to test `github.com/openkruise/kruise/pkg/controller/cloneset/revision` pkg.

``` shell
go test -timeout 180s -run ^TestCreateApplyRevision$ github.com/openkruise/kruise/pkg/controller/cloneset/revision -v
```

**What you expected to happen**:

The specified test case in `github.com/openkruise/kruise/pkg/controller/cloneset/revision` runs successfully .

**How to reproduce it (as minimally and precisely as possible)**:

``` shell
go test -timeout 180s -run ^TestCreateApplyRevision$ github.com/openkruise/kruise/pkg/controller/cloneset/revision -v
```

**Anything else we need to know?**:

The root cause is that no `m.Run()` call, so no tests will run.

https://github.com/openkruise/kruise/blob/c27205573753f7785594d52ea0e85db1d8aeffc7/pkg/controller/cloneset/revision/cloneset_revision_test.go#L34

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

### PR DESCRIPTION
**Pull request by xiangpingjiang**
### Ⅰ. Describe what this PR does

fix no test cases actually run in controller_revision_test file
### Ⅱ. Does this pull request fix one issue?

fixes #1456

### CODE REVIEW

**Comment by ls-2018** [comment]
@xiangpingjiang Please merge into a commit.

**Comment by xiangpingjiang** [comment]
> @xiangpingjiang Please merge into a commit.

@ls-2018 
Done

**Comment by furykerry** [comment]
@xiangpingjiang can you rebase the master, the master had fixed some problem in e2e

**Comment by veophi** [comment]
> > @xiangpingjiang can you rebase the master, the master had fixed some problem in e2e
> 
> @furykerry There were still e2e tests failed

@xiangpingjiang  will fix soon

**Comment by furykerry** [comment]
@xiangpingjiang [veophi](https://github.com/veophi) just add another fix of e2e， can you rebase the master again ?

**Comment by xiangpingjiang** [comment]
> @xiangpingjiang [veophi](https://github.com/veophi) just add another fix of e2e， can you rebase the master again ?

done @furykerry

**Comment by xiangpingjiang** [comment]
> @xiangpingjiang [veophi](https://github.com/veophi) just add another fix of e2e， can you rebase the master again ?

@furykerry  done

**Comment by ls-2018** [comment]
@xiangpingjiang Please fix the error reported in CI.

**Comment by xiangpingjiang** [comment]
> @xiangpingjiang Please fix the error reported in CI.

@ls-2018  The failed CI is not because my code change.  It already exists https://github.com/openkruise/kruise/actions/runs/7261379372/job/19782445025

**Pull request merged**
