### PR TITLE
fix:add volumes that initcontainers used in sidecarset

### LINKED ISSUE #934: [BUG] sidecarset doesn't add volumes used by initContainers
**What happened**:
sidecarset doesn't add volumes used by initContainers, it will only add volumes used by sidecar containers instead, which cause 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
sidecarset.yaml
```
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  initContainers:
  - name: init-container
    image: busybox:latest
    command: [ "/bin/sh", "-c", "sleep 10 && echo 'init container success'" ]
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes: # this field will be merged into pod.spec.volumes
  - name: log-volume
    emptyDir: {}
```
pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: pod-1
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
```
-> kubectl apply -f pod.yaml
The Pod "nginx" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: "log-volume"
**Anything else we need to know?**:

**Environment**:
- Kruise version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

### PR DESCRIPTION
**Pull request by outgnaY**
### Ⅰ. Describe what this PR does
fix: sidecarset doesn't insert volumes used in volumeMounts of initContainers

### Ⅱ. Does this pull request fix one issue?

fixes #934

### CODE REVIEW

**Comment by Jeffwan** [comment]
The change looks good to me. Let's add some test cases similar like

https://github.com/openkruise/kruise/blob/2953c6c26acc1285be7ccabf50b03d4eb4ed3078/pkg/webhook/pod/mutating/sidecarset_test.go#L609

**Comment by FillZpp** [comment]
@outgnaY  Thanks. The DCO failed. Please `git commit --amend -s` to signoff yourself and force push again.

**Comment by FillZpp** [comment]
/lgtm

@outgnaY Thanks for working on this. Last comment - It seems the user name and email of your commit are not your github config (may be your private git config). Please first `git config user.name "YOUR_GITHUB_NAME"` and `git config user.email "YOUR_GITHUB_EMAIL"` in your local kruise repo and then force push again.

**Review by FillZpp — APPROVED** [review]
/lgtm

**Pull request merged**
