### PR TITLE
Bump deps k8s to 0.28

### LINKED ISSUE #1541: [feature request] Bump K8s dependency to 1.28
**What would you like to be added**:

**Why is this needed**:

### PR DESCRIPTION
**Pull request by liangyuanpeng**
### Ⅰ. Describe what this PR does

Fixes #1541

Need update controller-gen to 0.14, pending  for https://github.com/openkruise/kruise/pull/1562

### CODE REVIEW

**Comment by Daseinlux** [comment]
Is there any progress on this PR now?

**Comment by liangyuanpeng** [comment]
@Daseinlux  I will take it up on this weekend.

**Comment by ABNER-1** [comment]
Is there something new progress on this PR now?

**Comment by liangyuanpeng** [comment]
@Daseinlux  @ABNER-1 

I encountered some resistance and haven't taken the time to resolve it yet. feel free to open a PR work for it if you wan't waiting for this.

**Comment by liangyuanpeng** [comment]
closing...

**Pull request closed without merging**
