### PR TITLE
feat: add typos to GitHub action

### PR DESCRIPTION
**Pull request by hezhizhen**
### Ⅰ. Describe what this PR does

Add https://github.com/crate-ci/typos to ci.yaml and fix existing typos.

### CODE REVIEW

**Comment by furykerry** [comment]
great jobs! can you squash the commits into one?

**Comment by hezhizhen** [comment]
> great jobs! can you squash the commits into one?

Done. PTAL

**Review by furykerry — COMMENTED** [review]
/lgtm

**Comment by zmberg** [comment]
@hezhizhen  tks, very good job.

**Pull request merged**
