### PR TITLE
add KruiseDaemon feature check in imagepulljob mutating webhook

### PR DESCRIPTION
**Pull request by YoghurtFree**
Signed-off-by: YoghurtFree <1527927373@qq.com>

### Ⅰ. Describe what this PR does
When the featuregate "KruiseDaemon" is not enabled, the imagepullljob mutating webhook should not take effect, the same as imagepullljob validating webhook does.

### CODE REVIEW

**Review by FillZpp — COMMENTED** [review]
Same question, this is unnecessary since imagepulljob-validating-webhook has checked the featureGate.

**Comment by YoghurtFree** [comment]
> Same question, this is unnecessary since imagepulljob-validating-webhook has checked the featureGate.

imagepulljob-mutating-webhook is excuted **before**  imagepulljob-validating-webhook, when the KruiseDaemon is not enabled, the imagepulljob-mutating-webhook should not be excuted, just a waste of time. the sooner the process is terminated, the better .

**Comment by FillZpp** [comment]
> imagepulljob-mutating-webhook is excuted **before** imagepulljob-validating-webhook, when the KruiseDaemon is not enabled, the imagepulljob-mutating-webhook should not be excuted, just a waste of time. the sooner the process is terminated, the better .

I understand your concern. But it may be weird that mutating webhook returns a validating error. Usually we believe mutating webhook only returns error when it got some internal server errors.

**Comment by YoghurtFree** [comment]
> > imagepulljob-mutating-webhook is excuted **before** imagepulljob-validating-webhook, when the KruiseDaemon is not enabled, the imagepulljob-mutating-webhook should not be excuted, just a waste of time. the sooner the process is terminated, the better .
> 
> I understand your concern. But it may be weird that mutating webhook returns a validating error. Usually we believe mutating webhook only returns error when it got some internal server errors.



> > imagepulljob-mutating-webhook is excuted **before** imagepulljob-validating-webhook, when the KruiseDaemon is not enabled, the imagepulljob-mutating-webhook should not be excuted, just a waste of time. the sooner the process is terminated, the better .
> 
> I understand your concern. But it may be weird that mutating webhook returns a validating error. Usually we believe mutating webhook only returns error when it got some internal server errors.

emm... maybe. I close this pr

**Pull request closed without merging**
