### PR TITLE
Optimize performance of LabelSelector conversion

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

### Ⅰ. Describe what this PR does
optimize-performance-of-label-selector-conversion

### CODE REVIEW

**Comment by hantmac** [comment]
Any benchmark data about two ways? I just curious 🤔

**Comment by FillZpp** [comment]
> Any benchmark data about two ways? I just curious 🤔

@hantmac I have added a benchmark test, but the UT action won't run it. I tested locally, it has nearly quadrupled the CPU and memory allocation.

```
BenchmarkValidatedLabelSelectorAsSelector-12    	10526553	      1111 ns/op	     640 B/op	      18 allocs/op
BenchmarkOriginalLabelSelectorAsSelector-12     	 3696250	      3329 ns/op	     941 B/op	      20 allocs/op
```

**Review by furykerry — COMMENTED** [review]
/lgtm

**Pull request merged**
