### PR TITLE
chore: remove vendor.

### LINKED ISSUE #1533: [feature request] Remove go mod vendor
**What would you like to be added**:
Kruise code currently contains go mod vendor, i think we should remove it.
**Why is this needed**:

### PR DESCRIPTION
**Pull request by liangyuanpeng**
### Ⅰ. Describe what this PR does

Fixes #1533
/assign @zmberg

### CODE REVIEW

**Comment by zmberg** [comment]
@liangyuanpeng Can you fix the failed check. https://github.com/openkruise/kruise/actions/runs/8497215787/job/23287275816?pr=1554

**Comment by liangyuanpeng** [comment]
Upgrades controller-gen from 0.11.0 to 0.14.0 to fix https://github.com/kubernetes-sigs/controller-tools/issues/880, and this it resolved by https://github.com/openkruise/kruise/pull/1562, so let's waiting for https://github.com/openkruise/kruise/pull/1562

**Comment by liangyuanpeng** [comment]
@zmberg PTAL Thanks

**Review by furykerry — COMMENTED** [review]
/lgtm

**Comment by furykerry** [comment]
@liangyuanpeng is the patch ready for merge? the patch is still labeled with "do-not-merge" label

**Comment by liangyuanpeng** [comment]
>  is the patch ready for merge?

Absolutely,Thanks for remind.

/hold cancel

**Pull request merged**
